# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  baseline-report.yaml
#   timestamp: 2026-09-21T14:50:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Bump(Enum):
    """
    Statically determined minimum version increment for this finding.
    """

    NONE = "none"
    PATCH = "patch"
    MINOR = "minor"
    MAJOR = "major"


class FindingCategory(Enum):
    """
    Classification of the changed aspect of the contract.
    """

    INTERFACE = "interface"
    ENVIRONMENT = "environment"
    BEHAVIOR = "behavior"
    METADATA = "metadata"


class Finding(BaseModel):
    """
    One detected change in the normalized CWL public contract.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    rule: Annotated[str, Field(title="Rule")]
    """
    Identifier of the comparison rule that produced this finding.
    """
    path: Annotated[str, Field(title="Path")]
    """
    Location in the normalized model, using JSON-Pointer-style escaping.
    """
    category: FindingCategory
    minimum_bump: Bump
    review_required: Annotated[bool | None, Field(title="Review Required")] = False
    """
    Whether this finding needs behavioral review; retained for auditing after global review classification.
    """
    message: Annotated[str, Field(title="Message")]
    """
    Human-readable explanation of the change.
    """
    before: Annotated[Any | None, Field(title="Before")] = None
    """
    Previous JSON value; null also represents an absent value when before_present is false.
    """
    after: Annotated[Any | None, Field(title="After")] = None
    """
    Current JSON value; null also represents an absent value when after_present is false.
    """
    before_present: Annotated[bool | None, Field(title="Before Present")] = True
    """
    Whether the previous value exists, distinguishing absence from explicit null.
    """
    after_present: Annotated[bool | None, Field(title="After Present")] = True
    """
    Whether the current value exists, distinguishing absence from explicit null.
    """


class BaselineReport(BaseModel):
    """
    CWL baseline comparison report. Required fields and defaults follow cwl_baseline.models.BaselineReport; the plugin serializes all fields, including defaults.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    schema_version: Annotated[str | None, Field(title="Schema Version")] = "1.0"
    """
    Report format version, currently 1.0.
    """
    previous_version: Annotated[str, Field(title="Previous Version")]
    """
    Semantic version of the previous released baseline.
    """
    current_version: Annotated[str, Field(title="Current Version")]
    """
    Declared semantic version of the current release.
    """
    minimum_bump: Bump
    minimum_version: Annotated[str, Field(title="Minimum Version")]
    """
    Previous version incremented once by minimum_bump.
    """
    suggested_version: Annotated[str | None, Field(title="Suggested Version")]
    """
    Minimum release version after review classification, or null while review remains unresolved.
    """
    review_required: Annotated[bool, Field(title="Review Required")]
    """
    Whether any behavioral review remains unresolved.
    """
    review_bump: Annotated[Bump | None, Field(title="Review Bump")] = None
    """
    Explicit global classification of changes requiring review, or null if none was supplied.
    """
    declared_version_sufficient: Annotated[bool, Field(title="Declared Version Sufficient")]
    """
    True when review is resolved and the current version meets or exceeds the suggested version.
    """
    findings: Annotated[list[Finding], Field(title="Findings", default_factory=list)]
    """
    Detailed changes contributing to the comparison; defaults to an empty list in the model.
    """


class Model(RootModel[BaselineReport]):
    root: BaselineReport
